import { LOG_IN, SIGN_UP, ME } from "@/api/auth.query";
import { PROJECT_ATTRIBUTES } from "@/api/attributes.query";
import {
  USER_PROJECTS,
  CREATE_PROJECT,
  DELETE_PROJECT,
  PROJECT_BY_ID
} from "@/api/projects.query";
import {
  DELETE_CHAPTER,
  CHAPTER_PARAGRAPHS,
  ANALYZE_CHAPTER
} from "@/api/chapters.query";
import {
  CREATE_ANNOTATION,
  PROJECT_ANNOTATIONS,
  DELETE_ANNOTATIONS
} from "@/api/annotation.query";
import {
  CREATE_ENTITY,
  PROJECT_ENTITIES,
  ALL_ENTITIES
} from "@/api/entities.query";

export {
  LOG_IN,
  SIGN_UP,
  ME,
  USER_PROJECTS,
  CREATE_PROJECT,
  DELETE_PROJECT,
  PROJECT_BY_ID,
  DELETE_CHAPTER,
  ANALYZE_CHAPTER,
  CHAPTER_PARAGRAPHS,
  CREATE_ENTITY,
  PROJECT_ENTITIES,
  ALL_ENTITIES,
  CREATE_ANNOTATION,
  PROJECT_ANNOTATIONS,
  DELETE_ANNOTATIONS,
  PROJECT_ATTRIBUTES
};
