export enum Icons {
  PaperClip = "mdi-paperclip",
  Earth = "mdi-earth",
  Pen = "mdi-pen",
  Plus = "mdi-plus",
  Night = "mdi-weather-night",
  Sunny = "mdi-weather-sunny",
  EyeOff = "mdi-eye-off",
  Eye = "mdi-eye",
  DocumentEdit = "mdi-file-document-edit-outline",
  File = "mdi-file",
  Lock = "mdi-lock",
  Folder = "mdi-folder",
  Cog = "mdi-cog",
  Account = "mdi-account",
  Cloud = "mdi-cloud-upload-outline",
  Menu = "mdi-menu",
  TextBoxCheck = "mdi-text-box-check",
  Dots = "mdi-dots-horizontal",
  Delete = "mdi-delete",
  DotVertical = "mdi-dots-vertical"
}
